import { Feedback, Tag } from '../types/feedback';
import { SentimentDataPoint, DepartmentMetrics, RiskIndicator, AIInsight } from '../types/analytics';

// Helper to create dates in the past
const daysAgo = (days: number): Date => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

// Helper to create realistic tags
const createTags = (...tags: Array<[string, string]>): Tag[] => {
  return tags.map(([type, value]) => ({
    type: type as Tag['type'],
    value,
  }));
};

// 30+ Realistic Feedback Entries
export const mockFeedback: Feedback[] = [
  {
    id: 'fb-001',
    timestamp: daysAgo(1),
    privacyLevel: 'anonymous',
    urgency: 'critical',
    content: 'The new deployment pipeline is causing severe delays. Three releases failed this week alone. Our team is working nights to fix issues that should have been caught in testing. This is unsustainable.',
    sentiment: -1,
    tags: createTags(['topic', 'deployment'], ['department', 'Engineering'], ['project', 'DevOps']),
    status: 'acknowledged',
    department: 'Engineering',
  },
  {
    id: 'fb-002',
    timestamp: daysAgo(2),
    privacyLevel: 'group',
    urgency: 'general',
    content: 'Loving the new flexible work policy! Being able to work from home 3 days a week has dramatically improved my work-life balance. Props to the leadership team for listening.',
    sentiment: 1,
    tags: createTags(['topic', 'work-life-balance'], ['topic', 'policy']),
    status: 'resolved',
    department: 'Marketing',
  },
  {
    id: 'fb-003',
    timestamp: daysAgo(3),
    privacyLevel: 'anonymous',
    urgency: 'priority',
    content: 'Communication between product and engineering is breaking down. We built an entire feature last sprint that product now says isn\'t what they wanted. Major waste of time and resources.',
    sentiment: -0.5,
    tags: createTags(['topic', 'communication'], ['department', 'Engineering'], ['department', 'Product']),
    status: 'in-progress',
    department: 'Engineering',
  },
  {
    id: 'fb-004',
    timestamp: daysAgo(4),
    privacyLevel: 'identified',
    urgency: 'general',
    content: 'Big shoutout to @Sarah Chen for mentoring me through my first major project! Her guidance on code review best practices was invaluable.',
    sentiment: 1,
    tags: createTags(['person', 'Sarah Chen'], ['topic', 'mentorship'], ['department', 'Engineering']),
    status: 'resolved',
    department: 'Engineering',
    employeeId: 'emp-142',
  },
  {
    id: 'fb-005',
    timestamp: daysAgo(5),
    privacyLevel: 'anonymous',
    urgency: 'priority',
    content: 'Our customer support tickets are piling up because the team is understaffed. Response times have doubled in the last month. We need more headcount or customers will start churning.',
    sentiment: -0.5,
    tags: createTags(['topic', 'staffing'], ['department', 'Support'], ['topic', 'workload']),
    status: 'acknowledged',
    department: 'Operations',
  },
  {
    id: 'fb-006',
    timestamp: daysAgo(7),
    privacyLevel: 'group',
    urgency: 'general',
    content: 'The Q3 all-hands was fantastic! Finally feel like I understand where the company is headed. More transparent updates like this please!',
    sentiment: 0.5,
    tags: createTags(['topic', 'communication'], ['topic', 'leadership']),
    status: 'resolved',
  },
  {
    id: 'fb-007',
    timestamp: daysAgo(8),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'Suggestion: Can we get standing desks or desk converters? Sitting all day is killing my back and several colleagues have mentioned the same issue.',
    sentiment: 0,
    tags: createTags(['topic', 'office'], ['topic', 'wellness']),
    status: 'in-progress',
  },
  {
    id: 'fb-008',
    timestamp: daysAgo(10),
    privacyLevel: 'anonymous',
    urgency: 'critical',
    content: 'There\'s concerning behavior from a senior team member that makes people uncomfortable. Multiple people have witnessed inappropriate comments during meetings. HR needs to address this.',
    sentiment: -1,
    tags: createTags(['topic', 'workplace-conduct'], ['topic', 'hr']),
    status: 'in-progress',
    department: 'Sales',
  },
  {
    id: 'fb-009',
    timestamp: daysAgo(12),
    privacyLevel: 'department',
    urgency: 'general',
    content: 'Our weekly sales team sync is too long. 90 minutes every Monday morning is excessive when most updates could be async. Can we trim to 30 mins?',
    sentiment: -0.5,
    tags: createTags(['topic', 'meetings'], ['department', 'Sales']),
    status: 'resolved',
    department: 'Sales',
  },
  {
    id: 'fb-010',
    timestamp: daysAgo(14),
    privacyLevel: 'identified',
    urgency: 'general',
    content: 'The #ProjectPhoenix team absolutely crushed the launch! Smooth rollout, zero downtime, and customer feedback is overwhelmingly positive. Great work everyone!',
    sentiment: 1,
    tags: createTags(['project', 'ProjectPhoenix'], ['topic', 'launch']),
    status: 'resolved',
    employeeId: 'emp-089',
  },
  {
    id: 'fb-011',
    timestamp: daysAgo(15),
    privacyLevel: 'anonymous',
    urgency: 'priority',
    content: 'Career growth feels stagnant. Been in the same role for 2 years with no clear path forward. Would love to see more transparent promotion criteria and growth opportunities.',
    sentiment: -0.5,
    tags: createTags(['topic', 'career-development'], ['topic', 'retention']),
    status: 'acknowledged',
    department: 'Engineering',
  },
  {
    id: 'fb-012',
    timestamp: daysAgo(16),
    privacyLevel: 'group',
    urgency: 'general',
    content: 'The new Figma license has been a game-changer for our design workflow. Thank you for approving the budget for this!',
    sentiment: 0.5,
    tags: createTags(['topic', 'tools'], ['department', 'Design']),
    status: 'resolved',
    department: 'Design',
  },
  {
    id: 'fb-013',
    timestamp: daysAgo(18),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'Office kitchen is constantly messy. People aren\'t cleaning up after themselves. Maybe we need clearer guidelines or more frequent cleaning service?',
    sentiment: -0.5,
    tags: createTags(['topic', 'office'], ['topic', 'culture']),
    status: 'in-progress',
  },
  {
    id: 'fb-014',
    timestamp: daysAgo(20),
    privacyLevel: 'anonymous',
    urgency: 'priority',
    content: 'The constant context switching is burning people out. I\'m on 4 different projects simultaneously and can\'t focus deeply on anything. We need better prioritization.',
    sentiment: -1,
    tags: createTags(['topic', 'workload'], ['topic', 'focus'], ['department', 'Engineering']),
    status: 'acknowledged',
    department: 'Engineering',
  },
  {
    id: 'fb-015',
    timestamp: daysAgo(21),
    privacyLevel: 'identified',
    urgency: 'general',
    content: 'Just wanted to say the new parental leave policy is amazing. I\'ll be using it next quarter and it means the world to my family. Thank you!',
    sentiment: 1,
    tags: createTags(['topic', 'benefits'], ['topic', 'policy']),
    status: 'resolved',
    employeeId: 'emp-201',
  },
  {
    id: 'fb-016',
    timestamp: daysAgo(23),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'Can we please upgrade to dual monitors as standard? Working on a single screen significantly slows down productivity for technical work.',
    sentiment: 0,
    tags: createTags(['topic', 'equipment'], ['topic', 'productivity']),
    status: 'in-progress',
    department: 'Engineering',
  },
  {
    id: 'fb-017',
    timestamp: daysAgo(25),
    privacyLevel: 'group',
    urgency: 'priority',
    content: 'Sales commission structure changed mid-quarter without proper communication. This directly impacts our compensation and feels unfair. Need urgent clarification.',
    sentiment: -1,
    tags: createTags(['topic', 'compensation'], ['department', 'Sales'], ['topic', 'transparency']),
    status: 'acknowledged',
    department: 'Sales',
  },
  {
    id: 'fb-018',
    timestamp: daysAgo(27),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'The onboarding process for new hires is chaotic. I started 3 weeks ago and still don\'t have access to half the tools I need. A more structured program would help.',
    sentiment: -0.5,
    tags: createTags(['topic', 'onboarding'], ['topic', 'process']),
    status: 'in-progress',
    department: 'Marketing',
  },
  {
    id: 'fb-019',
    timestamp: daysAgo(30),
    privacyLevel: 'department',
    urgency: 'general',
    content: 'Marketing team collaboration has been excellent lately! The shared content calendar and weekly brainstorms are really paying off.',
    sentiment: 0.5,
    tags: createTags(['department', 'Marketing'], ['topic', 'collaboration']),
    status: 'resolved',
    department: 'Marketing',
  },
  {
    id: 'fb-020',
    timestamp: daysAgo(32),
    privacyLevel: 'anonymous',
    urgency: 'priority',
    content: 'Remote employees feel like second-class citizens. Hybrid meetings default to in-person, remote folks get talked over, and social events are all office-based.',
    sentiment: -0.5,
    tags: createTags(['topic', 'remote-work'], ['topic', 'inclusion']),
    status: 'acknowledged',
  },
  {
    id: 'fb-021',
    timestamp: daysAgo(35),
    privacyLevel: 'identified',
    urgency: 'general',
    content: '@Marcus Johnson\'s workshop on public speaking was incredible! Already applying the techniques in my client presentations. More learning opportunities like this!',
    sentiment: 1,
    tags: createTags(['person', 'Marcus Johnson'], ['topic', 'learning'], ['topic', 'development']),
    status: 'resolved',
    employeeId: 'emp-067',
  },
  {
    id: 'fb-022',
    timestamp: daysAgo(37),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'The Slack noise is overwhelming. Too many channels, constant notifications, hard to find important info. We need better communication guidelines.',
    sentiment: -0.5,
    tags: createTags(['topic', 'communication'], ['topic', 'tools']),
    status: 'in-progress',
  },
  {
    id: 'fb-023',
    timestamp: daysAgo(40),
    privacyLevel: 'group',
    urgency: 'priority',
    content: 'PTO requests are taking forever to get approved. Submitted mine 6 weeks ago and still waiting. This makes it impossible to book travel with confidence.',
    sentiment: -0.5,
    tags: createTags(['topic', 'pto'], ['topic', 'process'], ['topic', 'hr']),
    status: 'acknowledged',
    department: 'Operations',
  },
  {
    id: 'fb-024',
    timestamp: daysAgo(42),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'Love that we\'re now doing monthly team lunches on the company card! Great for team bonding and shows the company values us.',
    sentiment: 0.5,
    tags: createTags(['topic', 'culture'], ['topic', 'benefits']),
    status: 'resolved',
  },
  {
    id: 'fb-025',
    timestamp: daysAgo(45),
    privacyLevel: 'anonymous',
    urgency: 'critical',
    content: 'The technical debt in our core product is reaching crisis levels. We\'re spending 60% of dev time on bug fixes instead of new features. Need dedicated time to refactor.',
    sentiment: -1,
    tags: createTags(['topic', 'technical-debt'], ['department', 'Engineering'], ['topic', 'product']),
    status: 'acknowledged',
    department: 'Engineering',
  },
  {
    id: 'fb-026',
    timestamp: daysAgo(48),
    privacyLevel: 'identified',
    urgency: 'general',
    content: 'The diversity & inclusion panel last week was eye-opening. Appreciate the company taking these conversations seriously. Looking forward to seeing action items.',
    sentiment: 0.5,
    tags: createTags(['topic', 'diversity'], ['topic', 'culture']),
    status: 'in-progress',
    employeeId: 'emp-178',
  },
  {
    id: 'fb-027',
    timestamp: daysAgo(50),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'Can we get a budget for professional development? Would love to attend conferences or take courses but can\'t afford it out of pocket.',
    sentiment: 0,
    tags: createTags(['topic', 'learning'], ['topic', 'benefits'], ['topic', 'career-development']),
    status: 'in-progress',
  },
  {
    id: 'fb-028',
    timestamp: daysAgo(53),
    privacyLevel: 'department',
    urgency: 'priority',
    content: 'Sales targets increased 40% this quarter with no additional support or resources. This feels unrealistic and is hurting morale across the entire team.',
    sentiment: -1,
    tags: createTags(['department', 'Sales'], ['topic', 'goals'], ['topic', 'morale']),
    status: 'acknowledged',
    department: 'Sales',
  },
  {
    id: 'fb-029',
    timestamp: daysAgo(55),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'The office temperature is either freezing or boiling - no in between. Can we get better climate control?',
    sentiment: -0.5,
    tags: createTags(['topic', 'office'], ['topic', 'comfort']),
    status: 'unread',
  },
  {
    id: 'fb-030',
    timestamp: daysAgo(58),
    privacyLevel: 'group',
    urgency: 'general',
    content: 'Huge win for the customer success team this month! We hit a 95% satisfaction score - highest ever. Team is crushing it!',
    sentiment: 1,
    tags: createTags(['department', 'Operations'], ['topic', 'customer-success']),
    status: 'resolved',
    department: 'Operations',
  },
  {
    id: 'fb-031',
    timestamp: daysAgo(60),
    privacyLevel: 'anonymous',
    urgency: 'priority',
    content: 'Manager feedback sessions feel performative. It\'s clear nothing actually changes based on our input. Either make it meaningful or don\'t waste our time.',
    sentiment: -0.5,
    tags: createTags(['topic', 'feedback'], ['topic', 'management'], ['topic', 'trust']),
    status: 'in-progress',
  },
  {
    id: 'fb-032',
    timestamp: daysAgo(62),
    privacyLevel: 'identified',
    urgency: 'general',
    content: 'The new health insurance plan is a massive upgrade! Mental health coverage especially is so important. Thank you for prioritizing employee wellness.',
    sentiment: 1,
    tags: createTags(['topic', 'benefits'], ['topic', 'wellness']),
    status: 'resolved',
    employeeId: 'emp-234',
  },
  {
    id: 'fb-033',
    timestamp: daysAgo(65),
    privacyLevel: 'anonymous',
    urgency: 'general',
    content: 'Idea: Could we do quarterly hack days where engineers can work on passion projects? Would boost creativity and morale.',
    sentiment: 0.5,
    tags: createTags(['topic', 'innovation'], ['department', 'Engineering'], ['topic', 'culture']),
    status: 'unread',
    department: 'Engineering',
  },
  {
    id: 'fb-034',
    timestamp: daysAgo(68),
    privacyLevel: 'anonymous',
    urgency: 'priority',
    content: 'Salary transparency would help a lot with retention. People are leaving because they find out they\'re underpaid compared to market or colleagues.',
    sentiment: -0.5,
    tags: createTags(['topic', 'compensation'], ['topic', 'retention'], ['topic', 'transparency']),
    status: 'acknowledged',
  },
  {
    id: 'fb-035',
    timestamp: daysAgo(70),
    privacyLevel: 'group',
    urgency: 'general',
    content: 'The marketing-sales alignment has improved dramatically since we started the weekly syncs. Lead quality is up and conversion rates are climbing!',
    sentiment: 0.5,
    tags: createTags(['department', 'Marketing'], ['department', 'Sales'], ['topic', 'collaboration']),
    status: 'resolved',
    department: 'Marketing',
  },
];

// Sentiment Timeline Data (90 days)
export const sentimentTimeline: SentimentDataPoint[] = [
  { date: '2024-08-13', overall: 0.6, engineering: 0.5, sales: 0.7, marketing: 0.8, operations: 0.5 },
  { date: '2024-08-20', overall: 0.65, engineering: 0.55, sales: 0.75, marketing: 0.8, operations: 0.6 },
  { date: '2024-08-27', overall: 0.7, engineering: 0.6, sales: 0.8, marketing: 0.85, operations: 0.65 },
  { date: '2024-09-03', overall: 0.55, engineering: 0.4, sales: 0.7, marketing: 0.75, operations: 0.5 },
  { date: '2024-09-10', overall: 0.5, engineering: 0.35, sales: 0.65, marketing: 0.7, operations: 0.45 },
  { date: '2024-09-17', overall: 0.45, engineering: 0.3, sales: 0.5, marketing: 0.65, operations: 0.5 },
  { date: '2024-09-24', overall: 0.4, engineering: 0.25, sales: 0.45, marketing: 0.6, operations: 0.45 },
  { date: '2024-10-01', overall: 0.5, engineering: 0.4, sales: 0.55, marketing: 0.7, operations: 0.5 },
  { date: '2024-10-08', overall: 0.55, engineering: 0.45, sales: 0.6, marketing: 0.75, operations: 0.55 },
  { date: '2024-10-15', overall: 0.6, engineering: 0.5, sales: 0.65, marketing: 0.8, operations: 0.6 },
  { date: '2024-10-22', overall: 0.65, engineering: 0.55, sales: 0.7, marketing: 0.85, operations: 0.65 },
  { date: '2024-10-29', overall: 0.7, engineering: 0.6, sales: 0.75, marketing: 0.9, operations: 0.7 },
  { date: '2024-11-05', overall: 0.75, engineering: 0.65, sales: 0.8, marketing: 0.9, operations: 0.75 },
  { date: '2024-11-12', overall: 0.72, engineering: 0.62, sales: 0.77, marketing: 0.88, operations: 0.72 },
];

// Department Metrics
export const departmentMetrics: DepartmentMetrics[] = [
  {
    department: 'Engineering',
    participationRate: 78,
    averageSentiment: 0.45,
    responseTime: 18,
    feedbackCount: 142,
  },
  {
    department: 'Sales',
    participationRate: 82,
    averageSentiment: 0.65,
    responseTime: 12,
    feedbackCount: 98,
  },
  {
    department: 'Marketing',
    participationRate: 85,
    averageSentiment: 0.75,
    responseTime: 8,
    feedbackCount: 67,
  },
  {
    department: 'Operations',
    participationRate: 71,
    averageSentiment: 0.58,
    responseTime: 24,
    feedbackCount: 89,
  },
  {
    department: 'Design',
    participationRate: 88,
    averageSentiment: 0.72,
    responseTime: 10,
    feedbackCount: 34,
  },
];

// Risk Indicators
export const riskIndicators: RiskIndicator[] = [
  {
    category: 'Retention Risk',
    level: 'high',
    metric: 7.2,
    trend: 'up',
    description: '7 employees mentioned career stagnation or compensation concerns in the last 30 days',
  },
  {
    category: 'Legal Exposure',
    level: 'medium',
    metric: 3,
    trend: 'stable',
    description: '3 reports of workplace conduct issues requiring HR attention',
  },
  {
    category: 'Project Health',
    level: 'high',
    metric: 65,
    trend: 'down',
    description: 'Technical debt and deployment issues impacting Engineering morale',
  },
  {
    category: 'Culture Breakdown',
    level: 'low',
    metric: 12,
    trend: 'down',
    description: 'Remote/hybrid friction mentioned in 12% of feedback',
  },
  {
    category: 'Communication',
    level: 'medium',
    metric: 18,
    trend: 'stable',
    description: 'Cross-team communication issues noted in 18% of recent feedback',
  },
  {
    category: 'Workload Stress',
    level: 'high',
    metric: 8,
    trend: 'up',
    description: '8 employees mentioned burnout, overwork, or context switching',
  },
];

// AI Insights
export const aiInsights: AIInsight[] = [
  {
    type: 'critical',
    title: 'Engineering Morale Crisis Developing',
    description: 'Sentiment in Engineering dropped 40% over the last 60 days. Primary drivers: technical debt (mentioned 12x), deployment issues (8x), and career growth concerns (7x). Retention risk is high.',
    impact: 'high',
    relatedFeedbackIds: ['fb-001', 'fb-003', 'fb-011', 'fb-014', 'fb-025'],
  },
  {
    type: 'trending-up',
    title: 'Flexible Work Policy Driving Engagement',
    description: 'The new flexible work policy has been mentioned positively 15 times since launch. Work-life balance sentiment improved 25% company-wide. Strong employee approval.',
    impact: 'high',
    relatedFeedbackIds: ['fb-002'],
  },
  {
    type: 'trending-down',
    title: 'Sales Team Confidence Declining',
    description: 'Sales team sentiment dropped 15% this quarter. Commission structure changes and increased targets without support are creating frustration. 4 mentions of morale issues.',
    impact: 'medium',
    relatedFeedbackIds: ['fb-017', 'fb-028'],
  },
  {
    type: 'hidden',
    title: 'Onboarding Experience Needs Attention',
    description: 'New hires (< 90 days) report significantly lower satisfaction. Common themes: missing tool access, lack of structure, unclear expectations. Affects 23% of new employee feedback.',
    impact: 'medium',
    relatedFeedbackIds: ['fb-018'],
  },
  {
    type: 'action-required',
    title: 'Workplace Conduct Issue Requires Immediate HR Follow-Up',
    description: 'Anonymous report of inappropriate behavior from senior team member. Multiple witnesses mentioned. Legal and culture risk if not addressed promptly.',
    impact: 'high',
    relatedFeedbackIds: ['fb-008'],
  },
];

// Culture Health Score
export const cultureHealthScore = {
  current: 72,
  previous: 65,
  trend: ((72 - 65) / 65) * 100, // +10.77%
};
